Add these missing functions
I'm only seeing "undefined reference to ..." errors in the CMake
build on a specific machine; I'm not sure why they're only cropping
up in that scenario.

I think these functions are only referenced from dead functions,
and in other environments the chains get dead-stripped.