Makefile: include gtest headers with '-isystem'
gtest does not compile successfully with "-Wundef", so the following
error will be produced while running unittests:

$ make run_gc_unittests

<snip>
 /path-to-deps/gtest-1.7.0/include/gtest/internal/gtest-port.h:288:6: error: 'GTEST_OS_WINDOWS' is not defined,
       evaluates to 0 [-Werror,-Wundef]
 #if !GTEST_OS_WINDOWS
     ^
 /path-to-deps/gtest-1.7.0/include/gtest/internal/gtest-port.h:299:5: error: 'GTEST_OS_LINUX_ANDROID' is not defined,
       evaluates to 0 [-Werror,-Wundef]
 #if GTEST_OS_LINUX_ANDROID
     ^
<snip>

The workaround for this issue is using '-isystem'.