Fix module type initialization
Add parameter names to module type __init__ and add tp_init slot. This
fixes a bug hit when using IPython caused by initializing ModuleType
with **kwargs:

    >> user_module = types.ModuleType("__main__", doc="foo")
    TypeError: () doesn't take keyword arguments

This use case is now tested in test/tests/modules.py and an IPython
integration test has been added