Makefile: lzma is required while running tests
The following error was produced when -llzma is not specified:

$ make check
cc -O2 -fPIC -Wimplicit -I../include -c ../test/test_extension/test.c -o ../test/test_extension/test.o -g
cc -shared ../test/test_extension/test.o -o ../test/test_extension/test.so -g
pyston: Compiling runtime/inline/link_forcer.o.bc
pyston: Compiling ../tools/publicize.o
pyston: Linking ../tools/publicize
elfxx.c:193: error: undefined reference to 'lzma_stream_footer_decode'
elfxx.c:200: error: undefined reference to 'lzma_index_buffer_decode'
elfxx.c:204: error: undefined reference to 'lzma_index_size'
elfxx.c:209: error: undefined reference to 'lzma_index_end'
elfxx.c:206: error: undefined reference to 'lzma_index_uncompressed_size'
elfxx.c:209: error: undefined reference to 'lzma_index_end'
elfxx.c:277: error: undefined reference to 'lzma_stream_buffer_decode'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [../tools/publicize] Error 1